config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users
  ActiveAdmin.routes(self)

  # ゲストログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root to: 'homes#top'
  get 'news' => 'homes#news'
  get 'following' => 'users#following'
  get 'followed' => 'users#followed'
  get 'confirm' => 'inquirys#confirm'
  get 'search/search'

  resources :users
  resources :hobby_images, only: %i[new create index show destroy] do
    resource :favorites, only: %i[create destroy]
    resources :image_comments, only: %i[create destroy]
  end
  resources :inquirys, only: %i[new create]

  # フォロー/フォロワーのルーティング
  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :hobby_image
end

app/models/hobby_image.rb
class HobbyImage < ApplicationRecord
  # 元々ある画像用モデル

  belongs_to :user
  has_many :image_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :images, dependent: :destroy
  accepts_attachments_for :images, attachment: :hobby

  validates :images, presence: true
  validates :body, length: { maximum: 600 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/home.rb
class Home < ApplicationRecord
  require 'mechanize'
end

app/models/image.rb
class Image < ApplicationRecord
  # 画像複数投稿のために制作したモデル

  belongs_to :hobby_image
  attachment :hobby
end

app/models/image_comment.rb
class ImageComment < ApplicationRecord
  belongs_to :user
  belongs_to :hobby_image
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  validates :address, presence: true
  validates :name, presence: true
  validates :message, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :hobby_images, dependent: :destroy
  has_many :image_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  attachment :user_image

  validates :name, presence: true, length: { maximum: 20 }
  validates :body, length: { maximum: 50 }
  validates :email, uniqueness: true

  # フォロー/フォロワー
  has_many :follower, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followed, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォロー確認をおこなう
  def following?(user)
    following_user.include?(user)
  end

  # 以下、メソッド化の例
  def follower_count
    follower.count
  end

  def followed_count
    followed.count
  end

  def current_user?(current_user)
    id == current_user.id
  end

  # ゲストログイン
  def self.guest
    find_or_create_by!(name: 'ゲスト', email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @images = HobbyImage.last(3)
  end

  def news
    agent = Mechanize.new
    page = agent.get('https://hobby.dengeki.com/') # urlの情報取得
    @elements = page.at('div.topnews') # atメソッドでdivクラスのtopnews内の情報を指定
    @elements = @elements.css('.ttlB').children  # cssメソッドでttlbの子要素を取得
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @model = params['model']
    @content = params['content']
    @how = params['how']
    if @model == 'User'
      @users = search_for(@how, @model, @content)
    else
      @images = search_for(@how, @model, @content)
    end
  end

  private

  def match(model, content)
    if model == 'User'
      User.where(name: content)
    elsif model == 'HobbyImage'
      HobbyImage.where(body: content)
    end
  end

  def partical(model, content)
    if model == 'User'
      User.where('name LIKE?', "%#{content}%")
    elsif model == 'HobbyImage'
      HobbyImage.where('body LIKE?', "%#{content}%")
    end
  end

  def search_for(how, model, content)
    case how
    when 'match'
      match(model, content)
    when 'partical'
      partical(model, content)
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to hobby_images_path
  end

  # def new
  #   super
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @hobby_images = @user.hobby_images.reverse_order
  end

  def following
    @user = User.find(params[:id])
    @users = @user.following_user
  end

  def followed
    @user = User.find(params[:id])
    @users = @user.follower_user
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:user_image, :name, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/hobby_images_helper.rb
module HobbyImagesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/image_comments_helper.rb
module ImageCommentsHelper
end

app/helpers/inquirys_helper.rb
module InquirysHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<% if current_user.following?(user) %>
  <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST, remote: true, class: 'text-danger' %>
<% else %>
  <%= link_to 'フォローする', follow_path(user.id), method: :POST, remote: true, class: 'text-success' %>
<% end %>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>件のエラーが発生しました
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<h2>プロフィール編集</h2>
<div class="container">
  <%= form_with model:@user, local:true do |f| %>
 <div class="row">
  <div class="col-sm-5">
   <!--画像プレビュー-->
   <img id="preview" style="width:40%;">
   <label for="inputImage">プロフィール画像</label>
   <%= f.attachment_field :user_image, placeholder: "プロフィール画像" %>
  </div>
  <div class="col-sm-7">
    <table>
     <!--ユーザー情報入力-->
     <tr><th><label for="inputName"><p>Name</p></label></th><td><%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%></td></tr>
     <tr><th><label for="inputBody"><p>introduction</p></label></th><td><%= f.text_area :body, autofocus: true, id:"inputBody", placeholder:"自己紹介"%></td></tr>
    </table>
   <%= f.submit "変更を保存" %>
  </div>
 </div>
 <% end %>
</div>


<!--画像プレビューのためのjs-->
<script>
  $('#user_user_image').on('change', function (e) {
    var reader = new FileReader();
    reader.onload = function (e) {
        $("#preview").attr('src', e.target.result);
    }
    reader.readAsDataURL(e.target.files[0]);
});
</script>

app/views/users/followed.html.erb
<h2>フォロワー</h2>

<% if @users.size  == 0 %>
  <p><%= "フォロワーはいません" %></p>
<% else %>
 <% @users.each do |user| %>
  <!--フォロワー画像-->
  <%= attachment_image_tag user, :user_image, size: "50x50", format: 'jpg', fallback: "no_image.jpg" %>
  <!--フォロワー名-->
  <%= link_to user_path(user) do %>
   <%= user.name %>
  <% end %>
 <% end %>
<% end %>

app/views/users/following.html.erb
<h2>フォロー</h2>

<% if @users.size  == 0 %>
  <p><%= "フォローしているユーザーはいません" %></p>
<% else %>
 <% @users.each do |user| %>
  <!--フォローユーザー画像-->
  <%= attachment_image_tag user, :user_image, size: "50x50", format: 'jpg', fallback: "no_image.jpg" %>
  <!--フォロー名-->
  <%= link_to user_path(user) do %>
   <%= user.name %>
  <% end %>
 <% end %>
<% end %>

app/views/users/show.html.erb
<div class="container">
<h1>マイページ</h1>
 <div class="row">
  <div class="col-sm-4">
   <!--プロフィール画像-->
   <%= attachment_image_tag @user, :user_image, size: "150x150", format: 'jpg', fallback: "no_image.jpg" %>
   <!--ユーザー名-->
   <h3><%= @user.name %></h3>
   <!--自己紹介-->
   <h5><%= @user.body %></h5>
   <!--フォロー-->
   <%= link_to following_path(id: @user.id) do %>
    <p>フォロー数:<%= @user.follower_count %></p>
   <% end %>
   <!--フォロワー-->
   <%= link_to followed_path(id: @user.id) do %>
    <p>フォロワー数:<%= @user.followed_count %></p>
   <% end %>
   <!--@user == current_userはmodelに定義-->
   <% unless @user.current_user?(current_user) %>
     <div id="follow_buttons_<%= @user.id %>">
      <%= render 'users/follow', user: @user %>
     </div>
   <% end %>
   <!--プロフィール編集リンク、@user == current_userはmodelに定義-->
   <% if @user.current_user?(current_user) %>
    <p><%= link_to "プロフィール編集", edit_user_path(@user) %></p>
   <% end %>
  </div>
   <div class="col-sm-8">
   <h3>投稿一覧</h3>
   <div class="images">
   <% @hobby_images.each do |hobby_image| %>
    <div class="user_card card mt-2 mr-1 shadow-lg ">
     <div>
      <!--投稿画像-->
      <% hobby_image.images.first(1).each do |image| %>
       <%= link_to hobby_image_path(hobby_image.id) do %>
        <%= attachment_image_tag image, :hobby, size: "100x100", format: 'jpg', fallback: "no_image.jpg" %>
       <% end %>
      <% end %>
     </div>
     <div class="card-comment">
      <!--コメント数-->
      <p><%= hobby_image.image_comments.count %>コメント</p>
     </div>
     <% if @user.current_user?(current_user) %>
      <%= link_to "削除", hobby_image_path(hobby_image.id), method: :delete %>
     <% end %>
    </div>
   <% end %>
   </div>
  </div>
 </div>
</div>