config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users
  ActiveAdmin.routes(self)

  # ゲストログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root to: 'homes#top'
  get 'news' => 'homes#news'
  get 'following' => 'users#following'
  get 'followed' => 'users#followed'
  get 'confirm' => 'inquirys#confirm'
  get 'search/search'

  resources :users
  resources :hobby_images, only: %i[new create index show destroy] do
    resource :favorites, only: %i[create destroy]
    resources :image_comments, only: %i[create destroy]
  end
  resources :inquirys, only: %i[new create]

  # フォロー/フォロワーのルーティング
  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :hobby_image
end

app/models/hobby_image.rb
class HobbyImage < ApplicationRecord
  # 元々ある画像用モデル

  belongs_to :user
  has_many :image_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :images, dependent: :destroy
  accepts_attachments_for :images, attachment: :hobby

  validates :images, presence: true
  validates :body, length: { maximum: 600 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/home.rb
class Home < ApplicationRecord
  require 'mechanize'
end

app/models/image.rb
class Image < ApplicationRecord
  # 画像複数投稿のために制作したモデル

  belongs_to :hobby_image
  attachment :hobby
end

app/models/image_comment.rb
class ImageComment < ApplicationRecord
  belongs_to :user
  belongs_to :hobby_image
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  validates :address, presence: true
  validates :name, presence: true
  validates :message, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :hobby_images, dependent: :destroy
  has_many :image_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  attachment :user_image

  validates :name, presence: true, length: { maximum: 20 }
  validates :body, length: { maximum: 50 }
  validates :email, uniqueness: true

  # フォロー/フォロワー
  has_many :follower, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followed, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォロー確認をおこなう
  def following?(user)
    following_user.include?(user)
  end

  # 以下、メソッド化の例
  def follower_count
    follower.count
  end

  def followed_count
    followed.count
  end

  def current_user?(current_user)
    id == current_user.id
  end

  # ゲストログイン
  def self.guest
    find_or_create_by!(name: 'ゲスト', email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @images = HobbyImage.last(3)
  end

  def news
    agent = Mechanize.new
    page = agent.get('https://hobby.dengeki.com/') # urlの情報取得
    @elements = page.at('div.topnews') # atメソッドでdivクラスのtopnews内の情報を指定
    @elements = @elements.css('.ttlB').children  # cssメソッドでttlbの子要素を取得
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @hobby_images = @user.hobby_images.reverse_order
  end

  def following
    @user = User.find(params[:id])
    @users = @user.following_user
  end

  def followed
    @user = User.find(params[:id])
    @users = @user.follower_user
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:user_image, :name, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/hobby_images_helper.rb
module HobbyImagesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inquirys_helper.rb
module InquirysHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title class="title">Hobby Graph!!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/e8f000d4c1.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

<!--ヘッダー部分-->

<header>
 <nav>
  <div class="container">
   <div class="row ">
     <div class="col-sm-4">
      <!--ロゴ-->
      <%= link_to root_path do %>
       <p></p><div class="logp"><%= image_tag 'hg-logo.png', size: "60x60" %>Hobby Graph!!</div></p>
      <% end %>
     </div>
     <div class="col-sm-8">
      <!--nav-->
      <ul class="nav float-right">
       <% if user_signed_in? %>
       <!--ログイン後-->
       <li class="nav-item">
        <%= link_to "マイページ", user_path(current_user.id) %>
       </li>
       <li class="nav-item">
        <%= link_to "新規投稿", new_hobby_image_path %>
       </li>
       <li class="nav-item">
        <%= link_to "投稿一覧", hobby_images_path %>
       </li>
       <li class="nav-item">
        <%=link_to "News", news_path %>
       </li>
       <li class="nav-item">
        <%= link_to "お問い合わせ", new_inquiry_path %>
       </li>
       <li class="nav-item">
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
       </li>
       <li>
        <!--検索ウィンドウ-->
        <%= form_with url: search_search_path, method: :get, local: true do |f| %>
         <%= f.text_field :content %>
         <%= f.select :model, [["User", "User"],["keyword","HobbyImage"]] %>
         <%= f.select :how, [["完全一致", "match"],["部分一致", "partical"]] %>
         <%= f.submit :search, class: "btn btn-success" %>
        <% end %>
       </li>
       <% else %>
       <!--ログイン前-->
       <li class="nav-item">
        <%= link_to "投稿一覧", hobby_images_path %>
       </li>
       <li class="nav-item">
        <%=link_to "News", news_path %>
       </li>
       <li class="nav-item">
        <%= link_to "ユーザー登録", new_user_registration_path %>
       </li>
       <li class="nav-item">
        <%= link_to "ログイン", new_user_session_path %>
       </li>
       <li class="nav-item">
        <%= link_to 'ゲストログイン', users_guest_sign_in_path, method: :post %>
       </li>
       <li>
        <!--検索ウィンドウ-->
        <!--<%= form_with url: search_search_path, method: :get, local: true do |f| %>-->
        <!-- <%= f.text_field :content %>-->
        <!-- <%= f.select :model, [["User", "User"],["keyword","HobbyImage"]] %>-->
        <!-- <%= f.select :how, [["完全一致", "match"],["部分一致", "partical"]] %>-->
        <!-- <%= f.submit :search %>-->
        <!--<% end %>-->
       </li>
       <% end %>
      </ul>
    </div>
   </div>
  </div>
 </nav>
</header>
<body>
 <% flash.each do |key, value| %>
  <div class="message">

  </div>
 <% end %>
 <%= yield %>
</body>
</html>